apiVersion: v1
kind: Service
metadata:
  name: bootnode
  namespace: ebc
  labels:
    app: bootnode
spec:
  selector:
    app: bootnode
  clusterIP: None
  ports:
  - name: discovery
    port: 30301
    protocol: UDP
  - name: http
    port: 8080