apiVersion: v1
kind: Service
metadata:
  name: bootnode-registrar
  namespace: ebc
  labels:
    app: bootnode-registrar
spec:
  selector:
    app: bootnode-registrar
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9898